const SESSION_ID = "SADIYA-MD=TtYwTC7L#M2q_z1p-zyO_pVHWKgtLpJe44TDXJZUekbmPKLwgQrE"
const GITHUB_USER_NAME = "jawadkhan112233"
const GITHUB_AUTH_TOKEN = ""
const DATABASE_REPO_NAME = "SADIYA-MD-DATABASE"

module.exports = {SESSION_ID,GITHUB_USER_NAME,GITHUB_AUTH_TOKEN,DATABASE_REPO_NAME}
